place/place/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from place import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('placeapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                           document_root=settings.MEDIA_ROOT)

place/placeapp/urls.py
from . import views
from django.urls import path
app_name= 'placeapp'
urlpatterns = [
    path('',views.home,name='home'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('edit/<int:id>/', views.update, name='update'),
    path('del/<int:id>/', views.delete, name='delete')
]

place/placeapp/models.py
from django.db import models

# Create your models here.

class place2visit(models.Model):
    img = models.ImageField(upload_to='pic')
    name = models.CharField(max_length=100)
    about = models.TextField()

    def __str__(self):
        return self.name

place/placeapp/forms.py
from django import forms
from . models import place2visit

class form1(forms.ModelForm):
    class Meta:
        model = place2visit
        fields = ['name', 'about', 'img']

place/placeapp/views.py
from django.shortcuts import render, redirect
from .models import place2visit
from . forms import form1

# Create your views here.
def home(request):
    var = place2visit.objects.all()
    var1 = {
        'result': var}

    return render(request, 'home.html', var1)

def detail(request, movie_id):
    var2 = place2visit.objects.get(id=movie_id)
    return render(request, 'detail.html', {'result': var2})

def add(request):
    if request.method == 'POST':
        NAME = request.POST.get('name',)
        ABOUT = request.POST.get('desc',)
        IMG = request.FILES['img']

        var = place2visit(name=NAME, about=ABOUT, img=IMG)
        var.save()
    return render(request, 'add.html')

def update( request,id ):
    movie = place2visit.objects.get(id=id)
    form = form1(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})

def delete( request,id ):
    if request.method == 'POST':
        var = place2visit.objects.get(id=id)
        var.delete()
        return redirect('/')
    return render(request, 'delete.html' )

place/templates/add.html
{% extends 'base.html' %}
{% block body %}
<div class="adddata">
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Movie Name"><br><br>
  <input type="text" name="desc" placeholder="About Movie"><br><br>
  <input type="file" name="img"><br><br>
  <input type="submit"><br><br>
</form>
  </div>
{% endblock %}

place/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href=" {% static 'styles.css' %} ">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
    <a style=" text-align: center; "class="navbar-brand" href="#"> MOVIE LIST </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

place/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
  {% csrf_token %}
  <h6>Are You Sure You Want To Delete?</h6>
  <input type="submit">
</form>
{% endblock %}

place/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="details">
     <div class="row">
         <div class="col-md-5">
             <img src=" {{result.img.url}} " width="400">
         </div>
         <div class="col-md-6">
             <b>{{result.name}}</b><br><br>
                   {{result.about}}<br><br>
                   <a id="btn" class="btn btn-warning" href="{% url 'placeapp:update' result.id %}"> update</a>
                   <a id="btn1" class="btn btn-danger" href="{% url 'placeapp:delete' result.id %}"> delete</a>
         </div>
     </div>
 </div>
{% endblock %}

place/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

place/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="new">
    <div class="row">
        {% for i in result %}
        <div class="col-md-3">
            <div class="card" style="width: 100%;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" >
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <a href="{% url 'placeapp:detail' i.id %}" class="btn btn-primary">view</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}